name: flutter_project_core
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  data_connection_checker_tv: ^0.3.5-nullsafety
  dio: ^4.0.0
  equatable: ^2.0.0
  mask_text_input_formatter: ^2.0.0-nullsafety.2
  intl: ^0.17.0
  logger: ^1.0.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^4.2.1
  dartz: ^0.10.0

dev_dependencies:
  # Test
  flutter_test:
    sdk: flutter
  faker: ^2.0.0-rc.2
  mocktail: ^0.1.2

  # Util
  import_sorter: ^4.6.0

import_sorter:
  emojis: false
  comments: false

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
